source 'https://github.com/CocoaPods/Specs.git'

project "LionheartExtensions.xcodeproj"

platform :ios, '10.3'

use_frameworks!

target 'LionheartExtensions_Example' do
  pod 'LionheartExtensions', :path => '../'

  target 'LionheartExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
  end
end
