source 'https://github.com/CocoaPods/Specs.git'

project "LionheartExtensions.xcodeproj"

use_frameworks!

target 'LionheartExtensions_Example' do
  pod 'LionheartExtensions', :path => '../'

  target 'LionheartExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.0'
    pod 'Nimble', '~> 4.0'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
