author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/LionheartExtensions"
github_file_prefix: "https://github.com/lionheart/LionheartExtensions/tree/5.1.1"
xcodebuild_arguments: ["-scheme", "LionheartExtensions", "-destination", "OS=18.0,name=iPhone 16 Pro"]
readme: "README.md"
copyright: "&copy; 2016-2017 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"
use_safe_filenames: true

